### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by prra-codes**
I have a made three bugs fixed and created this new-changes branch to set up the pull request.

### CODE REVIEW

**Comment by jacksongabbard** [comment]
Heya, I'm a bit confused. Your pull request title says bug fixes, but I don't actually see any?

**Comment by prra-codes** [comment]
Hey Jackson. I just made a pull request as you requested I should do so for
you to examine my code. I already made the fixes based on Tuesday's call
and there are no more bug fixes to make. I hope that is clear.

I was just wondering what the next step for the Connect 4 project is
though?

**Comment by prra-codes** [comment]
As I believe the Connect 4 game is complete in its current form.

**Comment by jacksongabbard** [comment]
Good question! So, the usual flow is that you raise pull requests for your
code before you commit to the main branch. One purpose of code review is to
ensure that your code is correct / as bug free as possible. Another purpose
of code review is to ensure your code is good code. So, we spent a bunch of
time confirming your code is correct, but we didn't spend any time on
whether the code is good code. To say it honestly, the code is pretty
rough. It's not the sort of code that would make a potential employer say,
"Oh wow — we've got to hire this guy!"

The idea of the game being "complete" is an interesting one. It depends on
what you want to define as success. If your idea of "complete" is "the code
works and the game functions correctly" — sure. The code is complete. But
if you define "complete" as "this is code that I can proudly show in my
portfolio and discuss with a potential employer" then I think you're
probably a lot further off than you realise.

The ideal thing from here would be for you to start revising the code one
small pull request at a time.

You should create pull requests for each one of the following tasks:
- Replace the generic create-react-app README file with a README that
explains what this repository actually is
- Remove all the random comments from the code that don't clarify what the
code is doing
- Remove the unnecessary stuff from the game state (you don't need
playerRed / setPlayerRed or playerYellow / setPlayerYellow — I can explain
if you need clarification)
- xPosition and yPosition are very misleading variable names they do not do
what they look like they do
- There are a lot of ways to improve the game to make it a showcase piece
— right now, it's the simplest thing that could possibly work, but you want
to show up something that goes beyond that
- As we discussed previously, you really want this to be running
server--side so that two people can play against one another, so setting up
a simple express server is a good move
- Altering your game logic to put the game state on the server is a big
change, but that's where you should go next after the above things

**Comment by prra-codes** [comment]
I understand, so complete code should mean that the code is correct AND it
is good code, and that's my aim with this project.

I definitely have questions, but I'll do as you recommend, doing the steps
one pull request at a time (and send you a quick message to let you know I
have one). I'll ask the relevant questions as I get to the task.

Thank you very much for clarifying the next steps and making me fully
understand the point of pull requests. I'll do things bit by bit.

**Comment by prra-codes** [comment]
Oh, and have an awesome weekend!

**Pull request closed without merging**
